pkg_install and pkg_get are now operational.

diff --git a/sea b/sea
--- a/sea
+++ b/sea
@@ -3,8 +3,8 @@
 # sea, the POSIX shell-script package manager
 SEA_VERSION=Work-in-progress
 # Setting default values if they don't exist
-[ -z $SEA_DATABASE ] || SEA_DATABASE="/etc/sea.d/"
-[ -z $SEA_INSTALL ] || SEA_INSTALL="/usr/bin/"
+[ -z $SEA_DATABASE ] && export SEA_DATABASE="/etc/sea.d"
+[ -z $SEA_INSTALL ] && export SEA_INSTALL="/usr/bin"
 
 log () {
     # print fancy outputs
@@ -66,21 +66,21 @@ pkg_get () {
     # Fetches a package.
     # The default repo is used, unless $3 exists.
     drepo=${2:-'https://sea.h3liu.ml'}
-
     packages=""
     # Get the categories.
+    mkdir /tmp/$$
     htmlret=$(curl "${drepo}/repo/" -s -o "/tmp/$$/categories" -w '%{http_code}') || die "Unable to fetch the repo categories."
     [ "${htmlret}" != "200" ] && die "ERROR ${htmlret}\n $(cat /tmp/$$/cateogries)"
-
     # Gets all the packages available
-    for x in /tmp/$$/categories; do
+    for x in $(cat /tmp/$$/categories); do
+        log "Current Category: ${x}"
         htmlret=$(curl "${drepo}/repo/${x}/" -s -o "/tmp/$$/packages" -w '%{http_code}') || die "Unable to fetch the repo packages."
         [ "${htmlret}" != "200" ] && die "ERROR ${htmlret}\n $(cat /tmp/$$/packages)"
 
-        for y in /tmp/$$/categories; do
+        for y in $(cat /tmp/$$/packages); do
             [ "${y}" = "${1}" ] && {
-                packages="/tmp/$$/$1"
-                curl "${drepo}/repo/${x}/${1}" -o "${packages}"
+                packages="/tmp/$$/$1.tar.gz"
+                curl "${drepo}/repo/${x}/${1}" -s -o "${packages}" || die "Package fetching failed."
                 break
             }
 
@@ -90,7 +90,7 @@ pkg_get () {
 
     # Returns nothing if no package has been found.
     # Else, return the path to the downloaded tarball.
-    print '%s' "${packages}"
+    printf '%s' "${packages}"
 }
 
 pkg_extract () {
@@ -104,8 +104,8 @@ pkg_depends () {
     # Resolves dependencies of a package.
     # Assumes that the directory has been created, and the PWD is the directory.
     if [ -e depends ]; then
-        while read -r line; do
-            if [ "$(command -v "$line" > /dev/null)" ]; then
+        for line in $(cat depends); do
+            if [ -e "$(command -v "$line")" ]; then
                 log "Dependency $line present."
             else
                 warn "Dependency $line missing."
@@ -121,19 +121,20 @@ pkg_depends () {
 
 pkg_install () {
     # Given one argument, the tarball for a package.
+    # Given another argument, the package name.
     pkg_extract "$1" || die "Unable to extract package."
     pkg_depends
     # Assumption is at this point, we are in the install directory.
-    while [ -e "$SEA_INSTALL/$1"]; do
+    while [ -e "$SEA_INSTALL/$1" ]; do
         log "The name of this package is taken. Please give another."
         read -r "$1"
     done
-    mkdir -p "$SEA_DATABASE/meta/$1"
-    cp depends "$SEA_DATABASE/meta/$1"
-    cp manifest "$SEA_DATABASE/meta/$1"
-    cp tags "$SEA_DATABASE/meta/$1"
-    printf "%s/%s" > "%s/meta/%s/location" "$SEA_INSTALL" "$1" "$SEA_INSTALL" "$1"
-    mv "$1" "$SEA_INSTALL"
+    mkdir -p "$SEA_DATABASE/meta/$2"
+    cp depends "$SEA_DATABASE/meta/$2"
+    cp manifest "$SEA_DATABASE/meta/$2"
+    cp tags "$SEA_DATABASE/meta/$2"
+    printf "${SEA_INSTALL}/$2" > "${SEA_DATABASE}/meta/${2}/location"
+    mv "package" "$SEA_INSTALL/$2"
 }
 
 pkg_remove () {
@@ -217,9 +218,10 @@ args () {
             # For loop for each requested packages
             for package in $@; do
                 # Fetches and installs every specified package.
-                pkg_install "$(pkg_get ${package})" || warn "Installation of ${package} has failed."
+                pkg_get "${package}" || die "Unable to fetch package."
+                pkg_install "/tmp/$$/${package}" "${package}" || warn "Installation of ${package} has failed."
             done
-            log "Packages has been successfully installed."
+            log "Packages has been installed."
         ;;
         q|query)
             shift 1
