Re-ordered, removed unneccessary newlines.

diff --git a/sea b/sea
--- a/sea
+++ b/sea
@@ -34,8 +34,44 @@ Actions:
     r, remove <pkg>      | remove package(s)
     s, submit <file>     | upload package for approval
     u, upgrade [pkg]     | update package(s) to latest versions
-    
+
 EOF
+}
+
+pkg_get () {
+    # Fetches a package.
+    # If $3 exists else pick default repo.
+    if [ $2 ]; then
+        drepo="$2"
+    else
+        drepo="https://sea.h3liu.ml"
+    fi
+
+    packages=""
+    # Get the categories.
+    htmlret=$(curl "$drepo/repo/" -s -o "/tmp/$$/categories" -w '%{http_code}') || die "Unable to fetch the repo categories."
+
+    if [ "$htmlret" != "200" ]; then
+        die "ERROR $htmlret\n $(cat /tmp/$$/cateogries)"
+    fi
+
+    # Gets all the packages available
+    for x in /tmp/$$/categories; do
+        htmlret=$(curl "$drepo/repo/$x/" -s -o "/tmp/$$/packages" -w '%{http_code}') || die "Unable to fetch the repo packages."
+        if [ "$htmlret" != "200" ]; then
+            die "ERROR $htmlret\n $(cat /tmp/$$/packages)"
+        fi
+
+        for y in /tmp/$$/categories; do
+            if [ "$y" == "$1" ]; then
+                packages=$packages"$x "
+                break
+            fi
+        done
+    done
+
+    # Return nothing if there are no categories available for the package.
+    printf "$packages"
 }
 
 pkg_extract () {
@@ -100,8 +136,6 @@ pkg_makepkg () {
     cd "$bfolder"
 }
 
-
-
 pkg_submit () {
     # submits package
     # If $3 exists else pick default repo.
@@ -125,40 +159,4 @@ pkg_submit () {
     fi
 
     rm -rf /tmp/$$/$1
-}
-
-pkg_get () {
-    # Fetches a package.
-    # If $3 exists else pick default repo.
-    if [ $2 ]; then
-        drepo="$2"
-    else
-        drepo="https://sea.h3liu.ml"
-    fi
-
-    packages=""
-    # Get the categories.
-    htmlret=$(curl "$drepo/repo/" -s -o "/tmp/$$/categories" -w '%{http_code}') || die "Unable to fetch the repo categories."
-    
-    if [ "$htmlret" != "200" ]; then
-        die "ERROR $htmlret\n $(cat /tmp/$$/cateogries)"
-    fi
-
-    # Gets all the packages available
-    for x in /tmp/$$/categories; do
-        htmlret=$(curl "$drepo/repo/$x/" -s -o "/tmp/$$/packages" -w '%{http_code}') || die "Unable to fetch the repo packages."
-        if [ "$htmlret" != "200" ]; then
-            die "ERROR $htmlret\n $(cat /tmp/$$/packages)"
-        fi
-
-        for y in /tmp/$$/categories; do
-            if [ "$y" == "$1" ]; then
-                packages=$packages"$x "
-                break
-            fi
-        done
-    done
-
-    # Return nothing if there are no categories available for the package.
-    printf "$packages"
 }
